ALTER TABLE clinics ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE clinics ADD COLUMN IF NOT EXISTS logo_url TEXT;

ALTER TABLE patients ADD COLUMN IF NOT EXISTS clinic_id UUID REFERENCES clinics(id) ON DELETE CASCADE;
ALTER TABLE patients ADD COLUMN IF NOT EXISTS name VARCHAR(255);
ALTER TABLE patients ADD COLUMN IF NOT EXISTS email VARCHAR(255);
ALTER TABLE patients ADD COLUMN IF NOT EXISTS phone VARCHAR(50);
ALTER TABLE patients ADD COLUMN IF NOT EXISTS status VARCHAR(30) NOT NULL DEFAULT 'active';
ALTER TABLE patients ALTER COLUMN user_id DROP NOT NULL;

CREATE INDEX IF NOT EXISTS idx_patients_clinic_id ON patients (clinic_id);